# Stage 1: Trained on large printed MER data
### model
model_name_or_path: /home/shiqilin/llm/qwen-ocr/Qwen2.5-VL-3B-Instruct-Pretrained
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: latex_ocr_tokenzied_train
template: qwen2_vl
cutoff_len: 4096
# max_samples: 1000 # used for debug
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2.5_vl-3b-ocr-stg1/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 5.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
weight_decay: 0.01
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
eval_dataset: latex_ocr_tokenzied_val, hmer_val
# val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

report_to: wandb
run_name: qwen2.5_vl-3b-ocr